### PR TITLE
Include IaaS services

### PR DESCRIPTION
**Pull request by adborden**
https://github.com/gsa/datagov-deploy/issues/2534

First pass of IaaS services.

Preview: https://github.com/GSA/datagov-compliance/blob/e5a0c4af09c54066ff659c5e6d873ebff9111acd/solr-service-scratchpad.md

### CODE REVIEW

**Comment by mogul** [comment]
Initial feedback: I think we should rename `Solr broker` to `EKS broker` in this diagram. Then add a separate `Solr broker` that explicitly manages the `Solr Instances` through an exposed k8s API endpoint. I think the `Solr ALB` will also end up being something more generic, eg `EKS ALB`.

**Comment by adborden** [comment]
Okay, I'll make those changes.

For the ALB, this is where my lack of K8S knowledge falls flat. Is it that there is a single ALB to route traffic for the entire cluster? Or does an ALB get created per solr service?

**Comment by mogul** [comment]
> Okay, I'll make those changes.
> 
> For the ALB, this is where my lack of K8S knowledge falls flat. Is it that there is a single ALB to route traffic for the entire cluster? Or does an ALB get created per solr service?

I thought that there would be a single one for the whole cluster, but it looks [deploying the AWS load-balancer controller](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) will create an ALB for each service. It looks like we still have the option of [using a single network load balancer in front of the nginx-ingress controller](https://aws.amazon.com/blogs/opensource/network-load-balancer-nginx-ingress-controller-eks/). I'm unclear on the cost implications of this, but imagine the former is more expensive, and likely overbuilt for what we're doing. cc @srinirei

**Comment by adborden** [comment]
Here's an updated preview: https://github.com/GSA/datagov-compliance/blob/06cc0556302265d0878d605db74d05fcbe39456c/solr-service-scratchpad.md

Not sure how much further to go, or if maybe we're tipping into a new diagram. Next is to add the Solr Operator. It wasn't clear to me looking at the SolrCloud helm charts if they stand on their own, or if it's really the Solr Operator that provisions new SolrCloud instances. If the latter, we want to update the diagram.

**Comment by mogul** [comment]
I'm going to break this up into two sets of diagrams, one for the EKS service, and another for the Solr service. I think that'll make them easier to understand, make them easier to modify in isolation, and make it easier to add additional services in future without making the diagram spaghetti.

**Review by mogul — APPROVED** [review]
(Merging in as-is since I can't work on your personal fork.)

**Pull request merged**
